<template>
  <div id="app">
    <img src="./assets/logo.png" />
    <div>
      <el-button type="primary" @click="handleOrder">Order Mask</el-button>
    </div>
  </div>
</template>

<script>
export default {
  name: "app",
  data() {
    return {
      pharmacies: [
        {
          id: 1,
          serviceName: "大连海王星辰医药有限公司春光街店",
          serviceAddress: "大连市沙河口区春光园1号",
          description: null,
          area: "沙河口区",
          phone: "15502620608",
          contacts: "王波",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.590034,
          latitude: 38.943215,
          businessHours: null,
          distance: null
        },
        {
          id: 2,
          serviceName: "大连海王星辰医药有限公司红凌路店",
          serviceAddress: "大连市沙河口区红凌路102号公建",
          description: null,
          area: "沙河口区",
          phone: "15542662089",
          contacts: "宋丽芳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.54055,
          latitude: 38.916473,
          businessHours: null,
          distance: null
        },
        {
          id: 3,
          serviceName: "大连海王星辰医药有限公司宏都筑景店",
          serviceAddress: "大连市沙河口区涟宁南园1-8、1-9、1-10",
          description: null,
          area: "沙河口区",
          phone: "15542662102",
          contacts: " 魏晓彤",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.569545,
          latitude: 38.890845,
          businessHours: null,
          distance: null
        },
        {
          id: 4,
          serviceName: "大连海王星辰医药有限公司马栏新店",
          serviceAddress: "大连市沙河口区兰田街40-42号",
          description: null,
          area: "沙河口区",
          phone: "15542662002",
          contacts: "温艳冲",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.565647,
          latitude: 38.929141,
          businessHours: null,
          distance: null
        },
        {
          id: 5,
          serviceName: "大连海王星辰医药有限公司民政店",
          serviceAddress: "大连市沙河口区民政街396号",
          description: null,
          area: "沙河口区",
          phone: "15542662027",
          contacts: "李雪云",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.595175,
          latitude: 38.91565,
          businessHours: null,
          distance: null
        },
        {
          id: 6,
          serviceName: "大连海王星辰医药有限公司台山村店",
          serviceAddress: "大连市沙河口区五一路142号20",
          description: null,
          area: "沙河口区",
          phone: "15542662150",
          contacts: "荣誉",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.573409,
          latitude: 38.904447,
          businessHours: null,
          distance: null
        },
        {
          id: 7,
          serviceName: "大连海王星辰医药有限公司太原街店",
          serviceAddress: "大连市沙河口区成仁街80号",
          description: null,
          area: "沙河口区",
          phone: "15542662069",
          contacts: "陈晶",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.601102,
          latitude: 38.906794,
          businessHours: null,
          distance: null
        },
        {
          id: 8,
          serviceName: "大连海王星辰医药有限公司星海公园店",
          serviceAddress: "大连市沙河口区西南路35号",
          description: null,
          area: "沙河口区",
          phone: "15542662130",
          contacts: "徐莉莉",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.569,
          latitude: 38.88613,
          businessHours: null,
          distance: null
        },
        {
          id: 9,
          serviceName: "大连鸿泰健康药房连锁有限公司连山街店",
          serviceAddress: "大连市沙河口区连山街涟宁园1号",
          description: null,
          area: "沙河口区",
          phone: "13130478001",
          contacts: "陈淑红",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.572504,
          latitude: 38.892779,
          businessHours: null,
          distance: null
        },
        {
          id: 10,
          serviceName: "大连鸿泰健康药房连锁有限公司联合路店",
          serviceAddress: "大连市沙河口区高尔基路242号",
          description: null,
          area: "沙河口区",
          phone: "13252948001",
          contacts: "邢丽霞",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.609607,
          latitude: 38.907277,
          businessHours: null,
          distance: null
        },
        {
          id: 11,
          serviceName: "大连美罗大药房连锁有限公司春柳店",
          serviceAddress: "大连市沙河口区学工街7号",
          description: null,
          area: "沙河口区",
          phone: "84416755",
          contacts: "姜丽",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.58499,
          latitude: 38.942882,
          businessHours: null,
          distance: null
        },
        {
          id: 12,
          serviceName: "大连美罗大药房连锁有限公司星海店  ",
          serviceAddress: "大连市沙河口区中山路624-2号",
          description: null,
          area: "沙河口区",
          phone: "84572520",
          contacts: "杜游",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.574763,
          latitude: 38.886863,
          businessHours: null,
          distance: null
        },
        {
          id: 13,
          serviceName: "国药控股国大药房沈阳连锁有限公司大连刘家桥药店",
          serviceAddress: "大连市沙河口区华北路406号",
          description: null,
          area: "沙河口区",
          phone: "19969882586",
          contacts: "董晶",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.57918,
          latitude: 38.949987,
          businessHours: null,
          distance: null
        },
        {
          id: 14,
          serviceName: "辽宁成大方圆医药连锁有限公司大连绿波小区分店",
          serviceAddress: "大连市沙河口西北路33-2号",
          description: null,
          area: "沙河口区",
          phone: "86706359",
          contacts: "康兆平",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.57341,
          latitude: 38.942456,
          businessHours: null,
          distance: null
        },
        {
          id: 15,
          serviceName: "辽宁成大方圆医药连锁有限公司大连西安路总店",
          serviceAddress: "大连市沙河口区西安路56号一层",
          description: null,
          area: "沙河口区",
          phone: "84507250",
          contacts: "于晓妮",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.594205,
          latitude: 38.919638,
          businessHours: null,
          distance: null
        },
        {
          id: 16,
          serviceName: "沈阳东北大药店连锁有限公司西安路店",
          serviceAddress: "大连市沙河口区成仁街9号",
          description: null,
          area: "沙河口区",
          phone: "84628689",
          contacts: "程晓华",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.595822,
          latitude: 38.918381,
          businessHours: null,
          distance: null
        },
        {
          id: 17,
          serviceName: "沈阳东北大药房连锁有限公司大连熟食品交易中心店",
          serviceAddress: "大连市沙河口区西南路568号西门头4号",
          description: null,
          area: "沙河口区",
          phone: "84387211",
          contacts: "刘景俊",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.570101,
          latitude: 38.91071,
          businessHours: null,
          distance: null
        },
        {
          id: 18,
          serviceName: "沈阳东北大药房连锁有限公司大连香沙店",
          serviceAddress: "大连市沙河口区香沙街海港货商1号楼3号",
          description: null,
          area: "沙河口区",
          phone: "84439850",
          contacts: "徐香华",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.594239,
          latitude: 38.934621,
          businessHours: null,
          distance: null
        },
        {
          id: 19,
          serviceName: "沈阳东北大药房连锁有限公司大连长春路店",
          serviceAddress: "大连市西岗区长春路360号",
          description: null,
          area: "西岗区",
          phone: "65975690",
          contacts: "田海英",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.64002,
          latitude: 38.893592,
          businessHours: null,
          distance: null
        },
        {
          id: 20,
          serviceName: "沈阳东北大药房连锁有限公司大连八一路店",
          serviceAddress: "大连市西岗区八一路106号",
          description: null,
          area: "西岗区",
          phone: "82671590",
          contacts: "吴荣",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.652601,
          latitude: 38.891125,
          businessHours: null,
          distance: null
        },
        {
          id: 21,
          serviceName: "大连海王星辰医药有限公司八一路店",
          serviceAddress: "大连市西岗区八一路200号",
          description: null,
          area: "西岗区",
          phone: "15542662028",
          contacts: "焦明艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.647851,
          latitude: 38.891329,
          businessHours: null,
          distance: null
        },
        {
          id: 22,
          serviceName: "大连海王星辰医药有限公司莲花小区店",
          serviceAddress: "大连市西岗区绕山路31号一层公建",
          description: null,
          area: "西岗区",
          phone: "15542662034",
          contacts: "王云风",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.614098,
          latitude: 38.90254,
          businessHours: null,
          distance: null
        },
        {
          id: 23,
          serviceName: "大连海王星辰医药有限公司胜利花园店",
          serviceAddress: "大连市西岗区胜利路101号",
          description: null,
          area: "西岗区",
          phone: "15642672687",
          contacts: "张波",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.616864,
          latitude: 38.909053,
          businessHours: null,
          distance: null
        },
        {
          id: 24,
          serviceName: "大连海王星辰医药有限公司北石道街店",
          serviceAddress: "大连市西岗区长春路288号",
          description: null,
          area: "西岗区",
          phone: "15542662138",
          contacts: "杨志红",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.631167,
          latitude: 38.900534,
          businessHours: null,
          distance: null
        },
        {
          id: 25,
          serviceName: "大连海王星辰医药有限公司万达华府店",
          serviceAddress: "辽宁省大连市西岗区黄河路326号公建",
          description: null,
          area: "西岗区",
          phone: "18525382373",
          contacts: "华中文",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.614899,
          latitude: 38.918107,
          businessHours: null,
          distance: null
        },
        {
          id: 26,
          serviceName: "大连海王星辰医药有限公司医大一院店",
          serviceAddress: "大连市西岗区珠江路71号、85号",
          description: null,
          area: "西岗区",
          phone: "13214220318",
          contacts: "曲雪",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.619769,
          latitude: 38.915076,
          businessHours: null,
          distance: null
        },
        {
          id: 27,
          serviceName: "大连海王星辰医药有限公司北海街店",
          serviceAddress: "大连市西岗区上海路100号1层",
          description: null,
          area: "西岗区",
          phone: "15542662142",
          contacts: "王冬艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.641978,
          latitude: 38.936898,
          businessHours: null,
          distance: null
        },
        {
          id: 28,
          serviceName: "大连海王星辰医药有限公司北岗桥店",
          serviceAddress: "辽宁省大连市西岗区北岗街17号一层部分共建",
          description: null,
          area: "西岗区",
          phone: "15502648070",
          contacts: "姜娜",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.622463,
          latitude: 38.928563,
          businessHours: null,
          distance: null
        },
        {
          id: 29,
          serviceName: "大连海王星辰医药有限公司金海花园店店",
          serviceAddress: "大连市西岗区金海西园34-7号",
          description: null,
          area: "西岗区",
          phone: "15542662008",
          contacts: "宋芳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.604777,
          latitude: 38.940937,
          businessHours: null,
          distance: null
        },
        {
          id: 30,
          serviceName: "辽宁成大方圆医药连锁有限公司大连工人村分店",
          serviceAddress: "大连市西岗区香锦街40号",
          description: null,
          area: "西岗区",
          phone: "84446335",
          contacts: "杨海燕",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.607202,
          latitude: 38.937587,
          businessHours: null,
          distance: null
        },
        {
          id: 31,
          serviceName: "辽宁成大方圆医药连锁有限公司大连福德街分店",
          serviceAddress: "大连市西岗区福德街39-45号",
          description: null,
          area: "西岗区",
          phone: "83692720",
          contacts: "王颍",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.621722,
          latitude: 38.923188,
          businessHours: null,
          distance: null
        },
        {
          id: 32,
          serviceName: "国药控股国大药房沈阳连锁有限公司大连同庆店",
          serviceAddress: "大连市西岗区群益街2号",
          description: null,
          area: "西岗区",
          phone: "19969882535",
          contacts: "徐春霞",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.628902,
          latitude: 38.922613,
          businessHours: null,
          distance: null
        },
        {
          id: 33,
          serviceName: "大连鸿泰健康药房连锁有限公司唐山街店",
          serviceAddress: "大连市西岗区红岩街安宁巷6号1单元1层1号",
          description: null,
          area: "西岗区",
          phone: "13236938001",
          contacts: "宋巧",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.634926,
          latitude: 38.917132,
          businessHours: null,
          distance: null
        },
        {
          id: 34,
          serviceName: "大连海王星辰医药有限公司华乐店",
          serviceAddress: "大连市中山区华乐街105号1层2号",
          description: null,
          area: "中山区",
          phone: "15542662068",
          contacts: "廉洪珍",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.687911,
          latitude: 38.921435,
          businessHours: null,
          distance: null
        },
        {
          id: 35,
          serviceName: "大连海王星辰医药有限公司桃源店",
          serviceAddress: "大连市中山区八一路26号一层",
          description: null,
          area: "中山区",
          phone: "15542662098",
          contacts: "李维平",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.65764,
          latitude: 38.891221,
          businessHours: null,
          distance: null
        },
        {
          id: 36,
          serviceName: "大连海王星辰医药有限公司友好店",
          serviceAddress: "大连市中山区玉光街39号",
          description: null,
          area: "中山区",
          phone: "15542662079",
          contacts: "张歉 ",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.647141,
          latitude: 38.923685,
          businessHours: null,
          distance: null
        },
        {
          id: 37,
          serviceName: "大连海王星辰医药有限公司中南路三店",
          serviceAddress: "大连市中山区中南路272号",
          description: null,
          area: "中山区",
          phone: "18525369582",
          contacts: "林岚",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.682794,
          latitude: 38.897948,
          businessHours: null,
          distance: null
        },
        {
          id: 38,
          serviceName: "大连美罗大药房连锁有限公司解放街店",
          serviceAddress: "大连市中山区柳林街12-1号",
          description: null,
          area: "中山区",
          phone: "82829711",
          contacts: "陈杰",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.653069,
          latitude: 38.921319,
          businessHours: null,
          distance: null
        },
        {
          id: 39,
          serviceName: "大连美罗大药房连锁有限公司五五路店    ",
          serviceAddress: "大连市中山区新乐里5号",
          description: null,
          area: "中山区",
          phone: "82950501",
          contacts: "郭杨 ",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.662601,
          latitude: 38.927591,
          businessHours: null,
          distance: null
        },
        {
          id: 40,
          serviceName: "国药控股国大药房沈阳连锁有限公司大连解放店",
          serviceAddress: "大连市中山区解放路318号",
          description: null,
          area: "中山区",
          phone: "19969882532",
          contacts: "宋敏",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.653608,
          latitude: 38.904252,
          businessHours: null,
          distance: null
        },
        {
          id: 41,
          serviceName: "国药控股国大药房沈阳连锁有限公司大连桃源店",
          serviceAddress: "大连市中山区白云街20号",
          description: null,
          area: "中山区",
          phone: "19969882517",
          contacts: "王绪玲",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.660176,
          latitude: 38.892493,
          businessHours: null,
          distance: null
        },
        {
          id: 42,
          serviceName: "辽宁成大方圆医药连锁有限公司大连青泥分店",
          serviceAddress: "大连市中山区友好街113号,大商交电旁",
          description: null,
          area: "中山区",
          phone: "83635534",
          contacts: "门丽红",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.638333,
          latitude: 38.923792,
          businessHours: null,
          distance: null
        },
        {
          id: 43,
          serviceName: "辽宁成大方圆医药连锁有限公司大连三八广场分店",
          serviceAddress: "大连市中山区顺阳街3号",
          description: null,
          area: "中山区",
          phone: "82735417",
          contacts: "原黎",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.665082,
          latitude: 38.924955,
          businessHours: null,
          distance: null
        },
        {
          id: 44,
          serviceName: "沈阳东北大药房连锁有限公司大连桃源街店",
          serviceAddress: "大连市中山区白云街66号一层",
          description: null,
          area: "中山区",
          phone: "16609807659",
          contacts: "姜宇",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.662211,
          latitude: 38.89168,
          businessHours: null,
          distance: null
        },
        {
          id: 45,
          serviceName: "国药控股国大药房沈阳连锁有限公司大连春德店",
          serviceAddress: "大连市中山区春德街96号",
          description: null,
          area: "中山区",
          phone: "19969882593",
          contacts: "刘艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.676621,
          latitude: 38.923617,
          businessHours: null,
          distance: null
        },
        {
          id: 46,
          serviceName: "大连海王星辰医药有限公司顺龙路店",
          serviceAddress: "大连高新技术产业园区龙王塘街道龙王塘村顺龙路256号-2",
          description: null,
          area: "高新园区",
          phone: "15542662017",
          contacts: "盛颖",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.40507,
          latitude: 38.847798,
          businessHours: null,
          distance: null
        },
        {
          id: 47,
          serviceName: "大连海王星辰医药有限公司大龙塘店",
          serviceAddress: "大连市旅顺口区龙塘镇官房村一层",
          description: null,
          area: "高新园区",
          phone: "15542662101",
          contacts: "孙秀秀",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.406163,
          latitude: 38.847665,
          businessHours: null,
          distance: null
        },
        {
          id: 48,
          serviceName: "大连海王星辰医药有限公司圣克拉店",
          serviceAddress: "大连市甘井子区红凌路771-4号部分公建",
          description: null,
          area: "高新园区",
          phone: "15566673359",
          contacts: "刘玉娥",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.531199,
          latitude: 38.896584,
          businessHours: null,
          distance: null
        },
        {
          id: 49,
          serviceName: "大连海王星辰医药有限公司大工店",
          serviceAddress: "辽宁省大连市甘井子区新新园102、104号",
          description: null,
          area: "高新园区",
          phone: "18525369538",
          contacts: "韩晶",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.531798,
          latitude: 38.893796,
          businessHours: null,
          distance: null
        },
        {
          id: 50,
          serviceName: "大连海王星辰医药有限公司大有恬园店",
          serviceAddress: "大连市甘井子区凌水路402号1单元1层4号",
          description: null,
          area: "高新园区",
          phone: "15542662219",
          contacts: "宋英丽",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.518326,
          latitude: 38.884101,
          businessHours: null,
          distance: null
        },
        {
          id: 51,
          serviceName: "大连海王星辰医药有限公司王家村新店",
          serviceAddress: "大连市甘井子区凌水镇王家村",
          description: null,
          area: "高新园区",
          phone: "15542662173",
          contacts: "张芳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.527719,
          latitude: 38.882973,
          businessHours: null,
          distance: null
        },
        {
          id: 52,
          serviceName: "大连海王星辰医药有限公司依海店",
          serviceAddress: "大连市高新技术产业园区小平岛依海街50-1、2号",
          description: null,
          area: "高新园区",
          phone: "15542662391",
          contacts: "刘颖",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.507262,
          latitude: 38.840645,
          businessHours: null,
          distance: null
        },
        {
          id: 53,
          serviceName: "大连海王星辰医药有限公司听海街店",
          serviceAddress: "大连高新技术产业园区亲海园16A-3号",
          description: null,
          area: "高新园区",
          phone: "15542661712",
          contacts: "李俊",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.509207,
          latitude: 38.84249,
          businessHours: null,
          distance: null
        },
        {
          id: 54,
          serviceName: "大连海王星辰医药有限公司聚贤路店",
          serviceAddress: "大连高新技术产业园区聚贤路126号",
          description: null,
          area: "高新园区",
          phone: "15502628761",
          contacts: "付晓蓓",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.515272,
          latitude: 38.862616,
          businessHours: null,
          distance: null
        },
        {
          id: 55,
          serviceName: "大连海王星辰医药有限公司火炬路店",
          serviceAddress: "大连市高新技术产业园区火炬路16-4号",
          description: null,
          area: "高新园区",
          phone: "15566673371",
          contacts: "熊秀敏",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.515035,
          latitude: 38.865364,
          businessHours: null,
          distance: null
        },
        {
          id: 57,
          serviceName: "大连海王星辰医药有限公司七贤中路店",
          serviceAddress: "大连市甘井子区黄浦路620号部分公建",
          description: null,
          area: "高新园区",
          phone: "18624376183",
          contacts: "邵妍",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.532296,
          latitude: 38.860093,
          businessHours: null,
          distance: null
        },
        {
          id: 58,
          serviceName: "大连海王星辰医药有限公司五月汇新店",
          serviceAddress:
            "大连市甘井子区黄浦路526-586号地上一层10轴至15轴部分面积",
          description: null,
          area: "高新园区",
          phone: "15566673571",
          contacts: "李桃地",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.537516,
          latitude: 38.866695,
          businessHours: null,
          distance: null
        },
        {
          id: 59,
          serviceName: "大连海王星辰医药有限公司书香园店",
          serviceAddress: "大连市高新园区数码路南段27号",
          description: null,
          area: "高新园区",
          phone: "15542662023",
          contacts: "赵冬梅",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.552869,
          latitude: 38.883965,
          businessHours: null,
          distance: null
        },
        {
          id: 60,
          serviceName: "大连海王星辰医药有限公司杨树沟店",
          serviceAddress: "大连市沙河口区杨树街4-5号",
          description: null,
          area: "高新园区",
          phone: "15542662169",
          contacts: "李双双",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.553082,
          latitude: 38.884697,
          businessHours: null,
          distance: null
        },
        {
          id: 61,
          serviceName: "大连海王星辰医药有限公司数码路店",
          serviceAddress: "辽宁省大连市沙河口区数码路北段20-16号",
          description: null,
          area: "高新园区",
          phone: "15502629190",
          contacts: "单春艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.550078,
          latitude: 38.892122,
          businessHours: null,
          distance: null
        },
        {
          id: 62,
          serviceName: "辽宁百和堂大药房连锁有限公司大连福佳店",
          serviceAddress:
            "辽宁省大连市甘井子区大连湾街道居家园4-5号（大连新都综合市场有限公司内）",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "张莞",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.671888,
          latitude: 39.037642,
          businessHours: null,
          distance: null
        },
        {
          id: 63,
          serviceName: "辽宁百和堂大药房连锁有限公司大连李家店",
          serviceAddress: "辽宁省大连市甘井子区俪泊园65-10号",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王聪",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.712721,
          latitude: 39.037211,
          businessHours: null,
          distance: null
        },
        {
          id: 64,
          serviceName: "辽宁百和堂大药房连锁有限公司大连玉山路店",
          serviceAddress: "大连市甘井子区泡崖四区52号楼1层3号公建",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "孙欣欣",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.55153,
          latitude: 38.977238,
          businessHours: null,
          distance: null
        },
        {
          id: 65,
          serviceName: "辽宁百和堂大药房连锁有限公司大连由家店",
          serviceAddress:
            "辽宁省大连市甘井子区辛寨子街道由家村（大连宏达皮件有限公司西南角）",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "郝贵荣",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.479281,
          latitude: 38.994038,
          businessHours: null,
          distance: null
        },
        {
          id: 66,
          serviceName: "辽宁百和堂大药房连锁有限公司大连小辛店",
          serviceAddress: "辽宁省大连市甘井子区辛寨子街道辛吉街27号楼",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "毕玲玲",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.515933,
          latitude: 38.962565,
          businessHours: null,
          distance: null
        },
        {
          id: 67,
          serviceName: "大连海王星辰医药有限公司祥和花园店",
          serviceAddress: "大连市甘井子区南关岭镇姚家路71-5号",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王冬艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.621131,
          latitude: 39.031497,
          businessHours: null,
          distance: null
        },
        {
          id: 68,
          serviceName: "大连亚安大药房连锁有限公司正东店",
          serviceAddress: "千山路68-1号",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "袁萍",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.582965,
          latitude: 38.985266,
          businessHours: null,
          distance: null
        },
        {
          id: 69,
          serviceName: "辽宁成大方圆医药连锁有限公司大连千山路分店",
          serviceAddress: "辽宁省大连市甘井子区千山路22号1层东侧",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "尹超",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.589482,
          latitude: 38.985157,
          businessHours: null,
          distance: null
        },
        {
          id: 70,
          serviceName: "大连海王星辰医药有限公司汇善南园店",
          serviceAddress: "大连市甘井子区汇善南园23-6号",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王冬艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.588561,
          latitude: 38.998902,
          businessHours: null,
          distance: null
        },
        {
          id: 71,
          serviceName: "辽宁成大方圆医药连锁有限公司大连王家桥店",
          serviceAddress: "辽宁省大连市甘井子区王家桥30号楼一层公建",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王婷 ",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.584711,
          latitude: 38.96279,
          businessHours: null,
          distance: null
        },
        {
          id: 72,
          serviceName: "辽宁百和堂大药房连锁有限公司大连鹏生店",
          serviceAddress: "辽宁省大连市甘井子区泉水N3区21-2号",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王倩 ",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.646816,
          latitude: 39.022988,
          businessHours: null,
          distance: null
        },
        {
          id: 73,
          serviceName: "辽宁百和堂大药房连锁有限公司大连龙畔五期店",
          serviceAddress:
            "辽宁省大连市甘井子区泉水龙畔金泉K3（12-15龙腾爱心超市一层）",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王天洋",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.630925,
          latitude: 39.01482,
          businessHours: null,
          distance: null
        },
        {
          id: 74,
          serviceName: "国药控股国大药房沈阳连锁有限公司大连甘井子店",
          serviceAddress: "辽宁省大连市甘井子区甘南街7-10号",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "李红敬  ",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.632758,
          latitude: 38.980638,
          businessHours: null,
          distance: null
        },
        {
          id: 75,
          serviceName: "大连海王星辰医药有限公司前革店",
          serviceAddress: "大连市甘井子区辛寨子镇前革村9号",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王冬艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.526203,
          latitude: 38.994985,
          businessHours: null,
          distance: null
        },
        {
          id: 76,
          serviceName: "大连海王星辰医药有限公司中革店",
          serviceAddress: "大连市甘井子区革镇堡镇中街17-10号一层",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王冬艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.536907,
          latitude: 39.016131,
          businessHours: null,
          distance: null
        },
        {
          id: 77,
          serviceName: "大连海王星辰医药有限公司朗润园店",
          serviceAddress: "大连市甘井子区辛寨子街道前革村公建房B1-30号",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王冬艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.526203,
          latitude: 38.994985,
          businessHours: null,
          distance: null
        },
        {
          id: 78,
          serviceName: "大连海王星辰医药有限公司兰花小区店",
          serviceAddress: "大连市甘井子南华街A20号1-1",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王冬艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.544719,
          latitude: 38.952405,
          businessHours: null,
          distance: null
        },
        {
          id: 79,
          serviceName: "大连海王星辰医药有限公司湾家店",
          serviceAddress: "大连市甘井子区红旗中路170-4号",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王冬艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.547322,
          latitude: 38.931016,
          businessHours: null,
          distance: null
        },
        {
          id: 80,
          serviceName: "大连海王星辰医药有限公司湾家花园店",
          serviceAddress: "大连市甘井子区湾家花园2号",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王冬艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.543451,
          latitude: 38.932425,
          businessHours: null,
          distance: null
        },
        {
          id: 81,
          serviceName: "大连海王星辰医药有限公司红旗店",
          serviceAddress: "大连市甘井子区红旗中路祥和园5号",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王冬艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.549649,
          latitude: 38.93101,
          businessHours: null,
          distance: null
        },
        {
          id: 82,
          serviceName: "大连海王星辰医药有限公司前程街店",
          serviceAddress: "大连市甘井子区红旗东路83-8号公建",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王冬艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.555125,
          latitude: 38.929503,
          businessHours: null,
          distance: null
        },
        {
          id: 83,
          serviceName: "大连海王星辰医药有限公司驿城新居店",
          serviceAddress: "大连市甘井子区营城子街道前牧村驿城西街2号楼3号公建",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王冬艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.447803,
          latitude: 38.995159,
          businessHours: null,
          distance: null
        },
        {
          id: 84,
          serviceName: "大连海王星辰医药有限公司营城一店",
          serviceAddress: "辽宁省大连市甘井子区营城子宾馆(营城西路北)",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王冬艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.390252,
          latitude: 38.989799,
          businessHours: null,
          distance: null
        },
        {
          id: 85,
          serviceName: "辽宁百和堂大药房连锁有限公司大连前关中心店",
          serviceAddress: "辽宁省大连市甘井子区大连湾街道前关园6号楼5号门",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王月",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.674191,
          latitude: 39.047052,
          businessHours: null,
          distance: null
        },
        {
          id: 86,
          serviceName: "辽宁百和堂大药房连锁有限公司大连金地艺境店",
          serviceAddress: "辽宁省大连市甘井子区博艺南园22-8号",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "邵丹",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.666112,
          latitude: 39.043793,
          businessHours: null,
          distance: null
        },
        {
          id: 87,
          serviceName: "辽宁百和堂大药房连锁有限公司大连金玛店",
          serviceAddress: "辽宁省大连市甘井子区玉学街2号4单元1层1号 ",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "孙欣欣",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.557875,
          latitude: 38.980786,
          businessHours: null,
          distance: null
        },
        {
          id: 88,
          serviceName: "大连海王星辰医药有限公司美林地铁站店",
          serviceAddress: "大连市甘井子区张前路503号-7公建",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王冬艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.52223,
          latitude: 38.977231,
          businessHours: null,
          distance: null
        },
        {
          id: 89,
          serviceName: "大连海王星辰医药有限公司康馨园店",
          serviceAddress: "大连市甘井子区玉泉街8号康馨园1层",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王冬艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.561756,
          latitude: 38.986521,
          businessHours: null,
          distance: null
        },
        {
          id: 90,
          serviceName: "辽宁百和堂大药房连锁有限公司大连嘉鸿店",
          serviceAddress:
            "辽宁省大连市甘井子区春田路194-3,194-4号(大连嘉鸿农贸生鲜超市有限公司内)",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "卢松杰",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.468305,
          latitude: 38.979411,
          businessHours: null,
          distance: null
        },
        {
          id: 91,
          serviceName: "辽宁百和堂大药房连锁有限公司大连辛昌店",
          serviceAddress: "辽宁省大连市甘井子区新昌小区1-1-2号",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "苗婷婷",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.536041,
          latitude: 38.961049,
          businessHours: null,
          distance: null
        },
        {
          id: 92,
          serviceName: "大连亚安大药房连锁有限公司金家街店",
          serviceAddress: "大连市甘井子区金家街17楼5号",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "袁萍",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.601442,
          latitude: 38.976171,
          businessHours: null,
          distance: null
        },
        {
          id: 93,
          serviceName: "大连海王星辰医药有限公司钻石湾店",
          serviceAddress: "大连市甘井子区和信园2-1号",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王冬艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.618053,
          latitude: 38.958597,
          businessHours: null,
          distance: null
        },
        {
          id: 94,
          serviceName: "大连海王星辰医药有限公司椒东街店",
          serviceAddress: "大连市甘井子区椒东街22-5号",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王冬艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.619337,
          latitude: 38.976929,
          businessHours: null,
          distance: null
        },
        {
          id: 95,
          serviceName: "大连海王星辰医药有限公司樱花园店",
          serviceAddress: "辽宁省大连市甘井子区甘南路42-6号",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王冬艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.625599,
          latitude: 38.98481,
          businessHours: null,
          distance: null
        },
        {
          id: 96,
          serviceName: "大连亚安大药房连锁有限公司南关岭店",
          serviceAddress: "大连市甘井子区南关岭街道南关岭路44-4号",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "袁萍",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.602602,
          latitude: 39.022486,
          businessHours: null,
          distance: null
        },
        {
          id: 97,
          serviceName: "大连亚安大药房连锁有限公司民兴店",
          serviceAddress: "辽宁省大连市甘井子区南关岭镇姚家路13-3号",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "袁萍",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.617189,
          latitude: 39.028779,
          businessHours: null,
          distance: null
        },
        {
          id: 98,
          serviceName: "国药控股国大药房沈阳连锁有限公司大连松江店",
          serviceAddress: "辽宁省大连市甘井子区松江路与华中路交汇处良友金伴旁",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "李红敬  ",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.582274,
          latitude: 38.976456,
          businessHours: null,
          distance: null
        },
        {
          id: 99,
          serviceName: "大连亚安大药房连锁有限公司富强路店",
          serviceAddress: "辽宁省大连市甘井子区山东路商城109号B32",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "袁萍",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.584231,
          latitude: 38.981157,
          businessHours: null,
          distance: null
        },
        {
          id: 100,
          serviceName: "辽宁成大方圆医药连锁有限公司大连东北名苑分店",
          serviceAddress: "辽宁省大连市甘井子区芳茗园30号2单元1层1号",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王婷 ",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.595341,
          latitude: 38.961467,
          businessHours: null,
          distance: null
        },
        {
          id: 101,
          serviceName: "大连海王星辰医药有限公司促进店",
          serviceAddress: "大连市甘井子区促进路30#1-4单元",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王冬艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.583634,
          latitude: 38.95411,
          businessHours: null,
          distance: null
        },
        {
          id: 102,
          serviceName: "大连海王星辰医药有限公司周水前店",
          serviceAddress: "大连市甘井子区华北路9号",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王冬艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.574207,
          latitude: 38.953679,
          businessHours: null,
          distance: null
        },
        {
          id: 103,
          serviceName: "国药控股国大药房沈阳连锁有限公司大连泉水店",
          serviceAddress: "辽宁省大连市甘井子区泉水A2区10-1号",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "李红敬  ",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.611298,
          latitude: 39.004301,
          businessHours: null,
          distance: null
        },
        {
          id: 104,
          serviceName: "辽宁百和堂大药房连锁有限公司大连龙畔金泉店",
          serviceAddress: "辽宁省大连市甘井子区泉水H3区26号1单元1层1号",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "柳红莹",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.627575,
          latitude: 39.005603,
          businessHours: null,
          distance: null
        },
        {
          id: 105,
          serviceName: "辽宁百和堂大药房连锁有限公司大连欧尚店",
          serviceAddress: "  辽宁省大连市甘井子区泉水P1区79号 ",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "马全",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.639223,
          latitude: 39.015369,
          businessHours: null,
          distance: null
        },
        {
          id: 106,
          serviceName: "大连海王星辰医药有限公司文体街店",
          serviceAddress: "大连市甘井子区甘南街9#1-11",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王冬艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.633108,
          latitude: 38.980281,
          businessHours: null,
          distance: null
        },
        {
          id: 107,
          serviceName: " 大连海王星辰医药有限公司甘井子店 ",
          serviceAddress: "辽宁省大连市甘井子区甘井子路23号1号公建",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王冬艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.62661,
          latitude: 38.976086,
          businessHours: null,
          distance: null
        },
        {
          id: 108,
          serviceName: "大连海王星辰医药有限公司后革店",
          serviceAddress: "大连市甘井子区革镇堡后革村",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王冬艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.54308,
          latitude: 39.016733,
          businessHours: null,
          distance: null
        },
        {
          id: 109,
          serviceName:
            "国药控股国大药房沈阳连锁有限公司大连金三角广场店(位于革镇堡)",
          serviceAddress: "大连市甘井子区革镇堡镇镇中街17-4号",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "于宁",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.537185,
          latitude: 39.015618,
          businessHours: null,
          distance: null
        },
        {
          id: 110,
          serviceName: "大连海王星辰医药有限公司虹港路二店",
          serviceAddress: "大连市甘井子区虹港路16号1层公建",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王冬艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.554041,
          latitude: 38.964439,
          businessHours: null,
          distance: null
        },
        {
          id: 111,
          serviceName: "大连海王星辰医药有限公司郭东路店",
          serviceAddress:
            "大连市甘井子区迎客路7号沈阳空军大连周水子干休所1号楼7单元北侧一层",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王冬艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.561791,
          latitude: 38.960132,
          businessHours: null,
          distance: null
        },
        {
          id: 112,
          serviceName: "大连海王星辰医药有限公司贤林园店",
          serviceAddress: "大连市甘井子区贤林园7-1-5-7号公建",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王冬艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.549629,
          latitude: 38.958281,
          businessHours: null,
          distance: null
        },
        {
          id: 113,
          serviceName: "大连海王星辰医药有限公司虹霞东路店",
          serviceAddress:
            "大连市甘井子区郭东街金寓花园五期二号楼二单元一层三号",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王冬艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.55659,
          latitude: 38.959026,
          businessHours: null,
          distance: null
        },
        {
          id: 114,
          serviceName: "大连海王星辰医药有限公司民乐店",
          serviceAddress: "大连市甘井子区红旗东路47号",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王冬艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.557963,
          latitude: 38.928048,
          businessHours: null,
          distance: null
        },
        {
          id: 115,
          serviceName: "国药控股国大药房沈阳连锁有限公司大连保利店",
          serviceAddress: "大连市甘井子区红南东街7-5号",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "陈旭艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.541518,
          latitude: 38.929156,
          businessHours: null,
          distance: null
        },
        {
          id: 116,
          serviceName: "大连海王星辰医药有限公司盛世年华店",
          serviceAddress:
            "大连市甘井子区营泰街167号大连盛世年华购物广场一层1F3、1F4",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王冬艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.384215,
          latitude: 38.993416,
          businessHours: null,
          distance: null
        },
        {
          id: 117,
          serviceName: "大连海王星辰医药有限公司亿达春田店",
          serviceAddress: "大连市甘井子区融田西园36-6号",
          description: null,
          area: "甘井子区",
          phone: null,
          contacts: "王冬艳",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.459816,
          latitude: 38.985574,
          businessHours: null,
          distance: null
        },
        {
          id: 118,
          serviceName: "大连海王星辰医药有限公司西安路店",
          serviceAddress: "大连市沙河口区福佳新天地广场一层A区F001",
          description: null,
          area: "沙河口区",
          phone: "18525369574",
          contacts: "郝春梅",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.593981,
          latitude: 38.923105,
          businessHours: null,
          distance: null
        },
        {
          id: 119,
          serviceName: "大连海王星辰医药有限公司龙江路新店",
          serviceAddress: "大连市沙河口区龙江路10号",
          description: null,
          area: "沙河口区",
          phone: "18525369531",
          contacts: "杨萍",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.568383,
          latitude: 38.8925,
          businessHours: null,
          distance: null
        },
        {
          id: 120,
          serviceName: "大连海王星辰医药有限公司黑石礁店",
          serviceAddress: "大连市沙河口区黑石礁街32号1-4号公建",
          description: null,
          area: "沙河口区",
          phone: "15542662031",
          contacts: "孙庆英",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.563459,
          latitude: 38.878718,
          businessHours: null,
          distance: null
        },
        {
          id: 121,
          serviceName: "大连海王星辰医药有限公司景宾巷店",
          serviceAddress: "大连市沙河口区中山路621号",
          description: null,
          area: "沙河口区",
          phone: "15542662237",
          contacts: "刘畅",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.568349,
          latitude: 38.883424,
          businessHours: null,
          distance: null
        },
        {
          id: 122,
          serviceName: "大连海王星辰医药有限公司锦绣市场店",
          serviceAddress: "大连市沙河口区锦绣路46号",
          description: null,
          area: "沙河口区",
          phone: "18642800931",
          contacts: "经媛媛",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.55968,
          latitude: 38.948359,
          businessHours: null,
          distance: null
        },
        {
          id: 123,
          serviceName: "大连海王星辰医药有限公司锦华店",
          serviceAddress:
            "大连市沙河口区锦绣路锦华园D区51号楼南1-22轴，北1-19轴公建",
          description: null,
          area: "沙河口区",
          phone: "15542662041",
          contacts: "鲍文英",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.549683,
          latitude: 38.947764,
          businessHours: null,
          distance: null
        },
        {
          id: 124,
          serviceName: "大连海王星辰医药有限公司中帝花园店",
          serviceAddress: "大连市沙河口区新生路绿欧园7-5-2号三单元1层2号",
          description: null,
          area: "沙河口区",
          phone: "15542662179",
          contacts: "岳平",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.570232,
          latitude: 38.941816,
          businessHours: null,
          distance: null
        },
        {
          id: 125,
          serviceName: "大连海王星辰医药有限公司台山店",
          serviceAddress: "大连市沙河口区南沙街95号",
          description: null,
          area: "沙河口区",
          phone: "15542662024",
          contacts: "王娜",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.573811,
          latitude: 38.907936,
          businessHours: null,
          distance: null
        },
        {
          id: 126,
          serviceName: "大连海王星辰医药有限公司知心园店",
          serviceAddress: "大连市沙河口区五一路知心园27号2-1-2号",
          description: null,
          area: "沙河口区",
          phone: "18525369534",
          contacts: "万凌云",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.557338,
          latitude: 38.893988,
          businessHours: null,
          distance: null
        },
        {
          id: 127,
          serviceName: "大连海王星辰医药有限公司敦煌路店",
          serviceAddress: "大连市沙河口区华北路华新苑小区13号楼4号(大连银行旁)",
          description: null,
          area: "沙河口区",
          phone: "15542662005",
          contacts: "梁惠",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.588651,
          latitude: 38.939088,
          businessHours: null,
          distance: null
        },
        {
          id: 128,
          serviceName: "国药控股国大药房沈阳连锁有限公司大连新起屯店",
          serviceAddress: "大连市西岗区长春路374号",
          description: null,
          area: "西岗区",
          phone: "19969882577",
          contacts: "曲立晶",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.643556,
          latitude: 38.892585,
          businessHours: null,
          distance: null
        },
        {
          id: 129,
          serviceName: "大连海王星辰医药有限公司华录店",
          serviceAddress: "大连市高新园区黄浦路664号1-3号",
          description: null,
          area: "高新园区",
          phone: "15542662118",
          contacts: "何凯丽",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.529329,
          latitude: 38.857808,
          businessHours: null,
          distance: null
        },
        {
          id: 130,
          serviceName: "辽宁成大方圆医药连锁有限公司大连锦云分店",
          serviceAddress: "大连市沙河口锦石路35-39号",
          description: null,
          area: "沙河口区",
          phone: "88109139",
          contacts: "任成浩",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.562865,
          latitude: 38.943496,
          businessHours: null,
          distance: null
        },
        {
          id: 132,
          serviceName: "国药控股国大药房沈阳连锁有限公司大连山东路商城店",
          serviceAddress: "辽宁省大连市甘井子区山东路商城259号",
          description: null,
          area: "甘井子区",
          phone: "19969882509",
          contacts: "张晓微",
          stocks: 0,
          subscribeCount: 5,
          expireDay: 5,
          activityStatus: 1,
          longitude: 121.588831,
          latitude: 38.986248,
          businessHours: null,
          distance: null
        }
      ]
    };
  },
  methods: {
    handleOrder() {
      this.listQuery.page = 1;
      this.getList();
    }
  }
};
</script>

<style>
#app {
  font-family: "Avenir", Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
